language: node_js
sudo: true
node_js: 6
script:
- npm run lint
- npm run compile
deploy:
- provider: npm
  email: germanattanasio@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: watson-developer-cloud/ui-components
- provider: script
  script: npm run deploy
  on:
    branch: master
    repo: watson-developer-cloud/ui-components
  skip_cleanup: true
- provider: releases
  api_key: $GH_TOKEN
  on:
    tags: true
    repo: watson-developer-cloud/ui-components
  skip_cleanup: true
