language: node_js
sudo: true
node_js: 8
script:
- npm run lint
- npm run compile
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8
- provider: script
  script: npm run deploy
  on:
    branch: master
    repo: watson-developer-cloud/ui-components
  skip_cleanup: true
